Sprint 3 issue 13 createwhereareyounowscreen
BrightCoders-Institute/reto-reservacion-de-vuelos-team-1-radiant pull request #16
Opened 2023-07-08 01:20 UTC by landillo

#What did we do?

We created the "Where are you now?" screen and implemented. the necessary functionality, where we can choose a flight origin, view the selection result, and navigate to the next screen.

We also created the screen to select the flight destination and its functionality, where we can choose a destination and view the result.
![Screenshot_1688778519](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team-1-radiant/assets/44180680/319acdd6-3fa4-4cfd-bfde-164b61ba0499)
![Screenshot_1688778549](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team-1-radiant/assets/44180680/261f6f07-ec6d-4875-a9f1-e53cc3192645)
![Screenshot_1688778558](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team-1-radiant/assets/44180680/9cef6d6e-8558-402b-a4b0-1a3835a8a2fe)
![Screenshot_1688778563](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team-1-radiant/assets/44180680/548f091c-aa3c-406a-b902-6089cc6dc44e)
![Screenshot_1688778573](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team-1-radiant/assets/44180680/0d25ce6d-2627-4f85-9acd-cd69f6223248)

2023-07-08 01:28 UTC, AlbertoG22 approved these changes
Excellent job team, keep it up! 😀

2023-07-08 02:33 UTC, ecruz17 commented on ios/Podfile.lock
> +    - React-Core
I'd suggest to gitignore this file ;)

2023-07-08 02:34 UTC, ecruz17 commented on package-lock.json
and gitignore this file too ^^

2023-07-08 02:36 UTC, ecruz17 commented on src/navigation/StackNavigator.tsx
>  import { Dimensions } from 'react-native';
You should delete your unused imports

2023-07-08 02:37 UTC, ecruz17 approved these changes
Nice work! 🚀

2023-07-08 15:18 UTC, FranciscoSenestrari requested changes

2023-07-08 15:18 UTC, FranciscoSenestrari commented on src/appTheme/AppTheme.tsx
Delet comment

2023-07-08 15:18 UTC, FranciscoSenestrari commented on src/components/FlightInfo.tsx
Delet Comments and unused code

2023-07-08 15:18 UTC, FranciscoSenestrari commented on src/components/OriginDropDown.tsx
Formta code

2023-07-08 15:18 UTC, FranciscoSenestrari commented on src/interfaces/interfaces.tsx
delet unused code

2023-07-11 00:24 UTC, ShadowEnchanter approved these changes
Good Job!

2023-07-11 00:50 UTC, FranciscoSenestrari commented on src/navigation/StackNavigator.tsx
needs delete comments in the code

2023-07-11 00:50 UTC, FranciscoSenestrari commented on src/interfaces/interfaces.tsx
delete comments

2023-07-11 00:50 UTC, FranciscoSenestrari commented on src/appTheme/AppTheme.tsx
delete comments

2023-07-11 03:11 UTC, FranciscoSenestrari approved these changes

2023-07-11 03:15 UTC, merged