Design registration page
BrightCoders-Institute/reto-reservacion-de-vuelos-team-1-radiant pull request #3
Opened 2023-06-23 01:47 UTC by AMCernas

# Description

- What?: We decided to implement the design on the registration page.
- Why?: These changes will help us later when we add the functionality to register users in the app.

## Screenshots

![image](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-team-1-radiant/assets/91897457/4542f65c-bebb-4120-a33c-3bc60b69f4b7)

2023-06-23 02:01 UTC, AlbertoG22 approved these changes
Looks pretty similar, well done team!

2023-06-23 02:24 UTC, BrandonVG approved these changes

2023-06-23 21:42 UTC, montsegv-2 approved these changes
LGTM, good job team!

2023-06-23 23:22 UTC, montsegv-2 approved these changes
LGTM!

2023-06-23 23:23 UTC, Alfredo20164920 commented
Good job team :)

2023-06-23 23:26 UTC, Alfredo20164920 approved these changes
Nice job 👍🏽

2023-06-23 23:39 UTC, IvanCa27 approved these changes

2023-06-24 00:23 UTC, ShadowEnchanter approved these changes
Good!

2023-06-24 01:23 UTC, wiltrouble requested changes

2023-06-24 01:23 UTC, wiltrouble commented on src/components/SignUp.tsx
> +    //backgroundColor: '#2774D5',
remove this comment

2023-06-24 01:23 UTC, wiltrouble commented on src/components/SignUp.tsx
> +    //tintColor: '#2774D5',
remove this comment

2023-06-24 01:23 UTC, wiltrouble commented on src/components/SignUp.tsx
> +    alignItems: 'flex-start', // Cambia a 'flex-start' para alinear los elementos a la izquierda
remove the comment or change it to english

2023-06-24 01:42 UTC, wiltrouble approved these changes

2023-06-24 01:43 UTC, merged